name: Test the Bazel build
run-name: Testing the Bazel build
on: [push]
jobs:
  bazel-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: bazelbuild/setup-bazelisk@v2

      - run: bazelisk test --enable_bzlmod --test_output=errors ...
