name: Test the CMake build
run-name: Testing the CMake build
on: [push]
jobs:
  cmake-build:
    strategy:
      matrix:
        # TODO(devjgm): Add windows-latest support. But executing the command
        # below will need to say eggsample.exe.
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gets the latest CMake
        uses: lukka/get-cmake@latest

      - run: cmake -S. -Bcmake-out
      - run: cmake --build cmake-out
      - run: ./cmake-out/src/eggsample
