name: Test the CMake build
run-name: Testing the CMake build
on: [push]
jobs:
  cmake-build:
    strategy:
      matrix:
        # TODO(devjgm): Add windows-latest support. But executing the command
        # below will need to say eggsample.exe.
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gets the latest CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: "31a159c1cae2bf905299085d9ef01bdfea0ca7b8"

      # This is nasty. See if there's a way to get rid of this.
      - name: Installing pkg-config if on macOS
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install pkg-config
          else
            true
          fi

      - run: cmake -S. -Bcmake-out -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      - run: cmake --build cmake-out
      - run: ./cmake-out/src/eggsample
      - run: ctest --test-dir cmake-out --output-on-failure
